const DEFAULT_ROW_HEIGHT = 32;

const HEADER_HEIGHT = 32;

const HEADER_AND_TOTALS_HEIGHT = HEADER_HEIGHT * 2;

const PAGINATION_HEIGHT = 42;

const MAX_PAGE_SIZE = 250000;

const ROW_DATA_BUFFER_SIZE = 25;

const COLUMN_DATA_BUFFER_SIZE = 5;

export {
  DEFAULT_ROW_HEIGHT,
  HEADER_HEIGHT,
  HEADER_AND_TOTALS_HEIGHT,
  MAX_PAGE_SIZE,
  PAGINATION_HEIGHT,
  ROW_DATA_BUFFER_SIZE,
  COLUMN_DATA_BUFFER_SIZE,
};
