const DEFAULT_ROW_HEIGHT = 32;

const HEADER_HEIGHT = 32;

const PAGINATION_HEIGHT = 42;

const MAX_PAGE_SIZE = 250000;

export { DEFAULT_ROW_HEIGHT, HEADER_HEIGHT, MAX_PAGE_SIZE, PAGINATION_HEIGHT };
