version: "2"
checks:
  method-lines:
    config:
      threshold: 60
  method-complexity:
    config:
      threshold: 8
  similar-code:
    enabled: true
    config:
      threshold: 3
exclude_patterns:
  - "src/**/*.spec.js"
  - "src/**/*.spec.jsx"
