version: '2'
plugins:
  duplication:
    config:
      languages:
        javascript:
          filters:
            - '(property (Identifier propTypes))'
          mass_threshold: 65
checks:
  method-lines:
    config:
      threshold: 100
  method-complexity:
    config:
      threshold: 10
exclude_patterns:
  - 'src/**/*.spec.js'
  - 'src/**/*.spec.jsx'
  - 'src/**/*.spec.ts'
  - 'src/**/*.spec.tsx'
  - '*config*'
  - 'test/**/__fixtures__'
  - 'theme'
  - 'mashup-example'
