version: "2"
plugins:
  duplication:
    config:
      languages:
        javascript:
          filters:
            - "(property (Identifier propTypes))"
          mass_threshold: 65
checks:
  method-lines:
    config:
      threshold: 80
  method-complexity:
    config:
      threshold: 10
exclude_patterns:
  - "src/**/*.spec.js"
  - "src/**/*.spec.jsx"
  - "*config*"
  - "test/**/__fixtures__"
  - "theme"
