version: "2"
plugins:
  duplication:
    config:
      languages:
        javascript:
          filters:
          - "s(:property, s(:Identifier, :propTypes))"
checks:
  method-lines:
    config:
      threshold: 60
  method-complexity:
    config:
      threshold: 8
exclude_patterns:
  - "src/**/*.spec.js"
  - "src/**/*.spec.jsx"
