version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        filters:
          - "(object (Identifier PropTypes))"
checks:
  method-lines:
    config:
      threshold: 60
  method-complexity:
    config:
      threshold: 8
exclude_patterns:
  - "src/**/*.spec.js"
  - "src/**/*.spec.jsx"
