export default () => ({
  type: 'sn-table',
  genericObjects: [
    {
      getLayout: {
        qInfo: {
          qId: 'LmuE',
          qType: 'sn-table',
        },
        qMeta: {
          privileges: ['read', 'update', 'delete', 'exportdata'],
        },
        qSelectionInfo: {},
        qHyperCube: {
          qSize: {
            qcx: 3,
            qcy: 1_000_000,
          },
          qDimensionInfo: [
            {
              qFallbackTitle: 'Product',
              qApprMaxGlyphCount: 37,
              qCardinal: 824,
              qSortIndicator: 'A',
              qGroupFallbackTitles: ['Product'],
              qGroupPos: 0,
              qStateCounts: {
                qLocked: 0,
                qSelected: 0,
                qOption: 824,
                qDeselected: 0,
                qAlternative: 0,
                qExcluded: 0,
                qSelectedExcluded: 0,
                qLockedExcluded: 0,
              },
              qTags: ['$key', '$ascii', '$text'],
              qDimensionType: 'D',
              qGrouping: 'N',
              qNumFormat: {
                qType: 'R',
                qnDec: 14,
                qUseThou: 1,
                qFmt: '##############',
                qDec: '.',
                qThou: ',',
              },
              qIsAutoFormat: true,
              qGroupFieldDefs: ['Line Desc 1'],
              qMin: 'NaN',
              qMax: 'NaN',
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qCardinalities: {
                qCardinal: 824,
                qHypercubeCardinal: 825,
                qAllValuesCardinal: -1,
              },
              qLibraryId: 'pmresb',
              title: 'Product',
              othersLabel: 'Others',
              autoSort: true,
              textAlign: {
                auto: true,
                align: 'left',
              },
              columnWidth: {
                type: 'auto',
                pixels: 200,
                percentage: 20,
              },
              cId: 'cmYsAf',
            },
          ],
          qMeasureInfo: [
            {
              qFallbackTitle: 'Sum([CostPrice])',
              qApprMaxGlyphCount: 8,
              qCardinal: 0,
              qSortIndicator: 'D',
              qNumFormat: {
                qType: 'R',
                qnDec: 14,
                qUseThou: 1,
                qFmt: '##############',
                qDec: '.',
                qThou: ',',
              },
              qMin: 0,
              qMax: 422.29,
              qIsAutoFormat: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qTrendLines: [],
              numFormatFromTemplate: true,
              autoSort: true,
              textAlign: {
                auto: true,
                align: 'left',
              },
              columnWidth: {
                type: 'auto',
                pixels: 200,
                percentage: 20,
              },
              cId: 'Sfgemzg',
            },
            {
              qApprMaxGlyphCount: 0,
              qCardinal: 0,
              qSortIndicator: 'N',
              qNumFormat: {
                qType: 'U',
                qnDec: 10,
                qUseThou: 0,
              },
              qMin: 0,
              qMax: 0,
              qError: {
                qErrorCode: 7005,
              },
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qTrendLines: [],
              numFormatFromTemplate: true,
              autoSort: true,
              textAlign: {
                auto: true,
                align: 'left',
              },
              columnWidth: {
                type: 'auto',
                pixels: 200,
                percentage: 20,
              },
              cId: 'Enjr',
            },
            {
              qFallbackTitle: 'Sum([Sales Price])',
              qApprMaxGlyphCount: 13,
              qCardinal: 0,
              qSortIndicator: 'D',
              qNumFormat: {
                qType: 'M',
                qnDec: 0,
                qUseThou: 0,
                qFmt: '$#,##0.00;($#,##0.00)',
                qDec: '.',
                qThou: ',',
              },
              qMin: -6681.480000000002,
              qMax: 322356.5599999992,
              qIsAutoFormat: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qTrendLines: [],
              numFormatFromTemplate: true,
              autoSort: true,
              textAlign: {
                auto: true,
                align: 'left',
              },
              columnWidth: {
                type: 'auto',
                pixels: 200,
                percentage: 20,
              },
              cId: 'UjGvg',
            },
          ],
          qEffectiveInterColumnSortOrder: [3, 0, 1],
          qGrandTotalRow: [
            {
              qText: '28734.15',
              qNum: 28734.15000000001,
              qElemNumber: -1,
              qState: 'X',
              qIsTotalCell: true,
            },
            {
              qText: '$6,734,059.91',
              qNum: 6734059.910000294,
              qElemNumber: -1,
              qState: 'X',
              qIsTotalCell: true,
            },
          ],
          qPivotDataPages: [],
          qStackedDataPages: [],
          qMode: 'S',
          qNoOfLeftDims: -1,
          qTreeNodesOnDim: [],
          qColumnOrder: [1, 0, 2, 3],
        },
        showTitles: true,
        title: '',
        subtitle: '',
        footnote: '',
        disableNavMenu: false,
        showDetails: true,
        showDetailsExpression: false,
        components: [
          {
            key: 'general',
          },
          {
            key: 'theme',
            header: {},
            content: {
              hoverEffect: true,
              hoverColor: {
                index: -1,
                color: '#5fdad3',
              },
              hoverFontColor: {
                index: -1,
                color: '#ec6738',
              },
            },
          },
        ],
        totals: {
          show: true,
          position: 'noTotals',
          label: 'Totals',
        },
        usePagination: true,
        enableChartExploration: false,
        chartExploration: {
          menuVisibility: 'auto',
        },
        visualization: 'sn-table',
      },
      getHyperCubeData: [
        {
          qMatrix: [
            [
              {
                qText: '81.82',
                qNum: 81.82000000000001,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Better Fancy Canned Sardines',
                qNum: 'NaN',
                qElemNumber: 66,
                qState: 'O',
              },
              {
                qText: '$322,356.56',
                qNum: 322356.5599999992,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '282.59',
                qNum: 282.59000000000003,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Atomic Mint Chocolate Bar',
                qNum: 'NaN',
                qElemNumber: 187,
                qState: 'O',
              },
              {
                qText: '$206,080.24',
                qNum: 206080.2399999999,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '255.38',
                qNum: 255.38,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Imagine Popsicles',
                qNum: 'NaN',
                qElemNumber: 45,
                qState: 'O',
              },
              {
                qText: '$199,688.92',
                qNum: 199688.92,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '119.99',
                qNum: 119.99000000000001,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Ebony Prepared Salad',
                qNum: 'NaN',
                qElemNumber: 127,
                qState: 'O',
              },
              {
                qText: '$194,111.81',
                qNum: 194111.8099999993,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '351.13',
                qNum: 351.13,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Red Spade Foot-Long Hot Dogs',
                qNum: 'NaN',
                qElemNumber: 322,
                qState: 'O',
              },
              {
                qText: '$191,216.32',
                qNum: 191216.32000000012,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '289.91',
                qNum: 289.91,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Discover Manicotti',
                qNum: 'NaN',
                qElemNumber: 104,
                qState: 'O',
              },
              {
                qText: '$171,364.97',
                qNum: 171364.9700000005,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '170.48',
                qNum: 170.48,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Moms Sliced Turkey',
                qNum: 'NaN',
                qElemNumber: 67,
                qState: 'O',
              },
              {
                qText: '$156,600.97',
                qNum: 156600.97000000015,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '422.29',
                qNum: 422.29,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Washington Apple Drink',
                qNum: 'NaN',
                qElemNumber: 619,
                qState: 'O',
              },
              {
                qText: '$154,208.52',
                qNum: 154208.51999999926,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '296.01',
                qNum: 296.01,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Red Spade Turkey Hot Dogs',
                qNum: 'NaN',
                qElemNumber: 118,
                qState: 'O',
              },
              {
                qText: '$136,982.12',
                qNum: 136982.12000000034,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '212.65',
                qNum: 212.65,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Bravo Large Canned Shrimp',
                qNum: 'NaN',
                qElemNumber: 342,
                qState: 'O',
              },
              {
                qText: '$111,780.05',
                qNum: 111780.05000000025,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '49.81',
                qNum: 49.81,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'High Top Walnuts',
                qNum: 'NaN',
                qElemNumber: 134,
                qState: 'O',
              },
              {
                qText: '$93,533.67',
                qNum: 93533.66999999997,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '167.72',
                qNum: 167.72,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Ebony Squash',
                qNum: 'NaN',
                qElemNumber: 78,
                qState: 'O',
              },
              {
                qText: '$92,078.68',
                qNum: 92078.67999999982,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '141.28',
                qNum: 141.28,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Cutting Edge Foot-Long Hot Dogs',
                qNum: 'NaN',
                qElemNumber: 63,
                qState: 'O',
              },
              {
                qText: '$75,727.43',
                qNum: 75727.43000000007,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '76',
                qNum: 76,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Red Spade Low Fat Bologna',
                qNum: 'NaN',
                qElemNumber: 49,
                qState: 'O',
              },
              {
                qText: '$74,984.17',
                qNum: 74984.17000000004,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '221.46',
                qNum: 221.46,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Even Better Strawberry Yogurt',
                qNum: 'NaN',
                qElemNumber: 186,
                qState: 'O',
              },
              {
                qText: '$74,266.60',
                qNum: 74266.60000000002,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '245.51',
                qNum: 245.51,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Red Spade Low Fat Cole Slaw',
                qNum: 'NaN',
                qElemNumber: 271,
                qState: 'O',
              },
              {
                qText: '$69,028.87',
                qNum: 69028.87000000002,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '72.2',
                qNum: 72.2,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Nationeel Avocado Dip',
                qNum: 'NaN',
                qElemNumber: 10,
                qState: 'O',
              },
              {
                qText: '$55,905.49',
                qNum: 55905.48999999997,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '262.62',
                qNum: 262.62,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Tell Tale Onions',
                qNum: 'NaN',
                qElemNumber: 312,
                qState: 'O',
              },
              {
                qText: '$55,707.57',
                qNum: 55707.56999999999,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '101.39',
                qNum: 101.39,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Big Time Frozen Cheese Pizza',
                qNum: 'NaN',
                qElemNumber: 79,
                qState: 'O',
              },
              {
                qText: '$51,313.39',
                qNum: 51313.39,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '108.18',
                qNum: 108.18,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Thresher Spicy Mints',
                qNum: 'NaN',
                qElemNumber: 62,
                qState: 'O',
              },
              {
                qText: '$50,480.77',
                qNum: 50480.769999999895,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '141.49',
                qNum: 141.49,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Gorilla Jack Cheese',
                qNum: 'NaN',
                qElemNumber: 346,
                qState: 'O',
              },
              {
                qText: '$48,856.39',
                qNum: 48856.389999999956,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '79.62',
                qNum: 79.62,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Golden Frozen Chicken Thighs',
                qNum: 'NaN',
                qElemNumber: 42,
                qState: 'O',
              },
              {
                qText: '$45,693.30',
                qNum: 45693.299999999974,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '79.86',
                qNum: 79.86,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'High Top Oranges',
                qNum: 'NaN',
                qElemNumber: 340,
                qState: 'O',
              },
              {
                qText: '$45,539.43',
                qNum: 45539.43000000011,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '80.88',
                qNum: 80.88,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Bravo Canned Yams',
                qNum: 'NaN',
                qElemNumber: 126,
                qState: 'O',
              },
              {
                qText: '$44,732.40',
                qNum: 44732.39999999998,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '250.89',
                qNum: 250.89000000000001,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Even Better Chocolate Milk',
                qNum: 'NaN',
                qElemNumber: 664,
                qState: 'O',
              },
              {
                qText: '$44,056.42',
                qNum: 44056.42000000002,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '91.61',
                qNum: 91.61,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Token Apple Drink',
                qNum: 'NaN',
                qElemNumber: 371,
                qState: 'O',
              },
              {
                qText: '$42,947.09',
                qNum: 42947.089999999946,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '78.83',
                qNum: 78.83,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Ebony Macintosh Apples',
                qNum: 'NaN',
                qElemNumber: 19,
                qState: 'O',
              },
              {
                qText: '$39,961.85',
                qNum: 39961.850000000035,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '32.7',
                qNum: 32.7,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Tell Tale Limes',
                qNum: 'NaN',
                qElemNumber: 43,
                qState: 'O',
              },
              {
                qText: '$39,091.02',
                qNum: 39091.01999999999,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '123.99',
                qNum: 123.99000000000001,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Best Choice Sugar Cookies',
                qNum: 'NaN',
                qElemNumber: 433,
                qState: 'O',
              },
              {
                qText: '$38,556.19',
                qNum: 38556.18999999995,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '83.12',
                qNum: 83.12,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Colony Wheat Bread',
                qNum: 'NaN',
                qElemNumber: 99,
                qState: 'O',
              },
              {
                qText: '$37,590.90',
                qNum: 37590.89999999995,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '129.86',
                qNum: 129.86,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Monarch Ravioli',
                qNum: 'NaN',
                qElemNumber: 408,
                qState: 'O',
              },
              {
                qText: '$36,181.48',
                qNum: 36181.479999999996,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '66.16',
                qNum: 66.16,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Blue Label Canned Beets',
                qNum: 'NaN',
                qElemNumber: 9,
                qState: 'O',
              },
              {
                qText: '$35,947.19',
                qNum: 35947.18999999999,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '57.56',
                qNum: 57.56,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Gorilla Chocolate Milk',
                qNum: 'NaN',
                qElemNumber: 72,
                qState: 'O',
              },
              {
                qText: '$34,402.28',
                qNum: 34402.280000000064,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '129.7',
                qNum: 129.7,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Landslide White Sugar',
                qNum: 'NaN',
                qElemNumber: 191,
                qState: 'O',
              },
              {
                qText: '$34,205.79',
                qNum: 34205.78999999997,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '392.3',
                qNum: 392.3,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Fabulous Mango Drink',
                qNum: 'NaN',
                qElemNumber: 713,
                qState: 'O',
              },
              {
                qText: '$33,394.76',
                qNum: 33394.76000000001,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '51.93',
                qNum: 51.93,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Bravo Canned Tomatos',
                qNum: 'NaN',
                qElemNumber: 44,
                qState: 'O',
              },
              {
                qText: '$33,138.81',
                qNum: 33138.810000000005,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '136.52',
                qNum: 136.52,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Even Better 2% Milk',
                qNum: 'NaN',
                qElemNumber: 680,
                qState: 'O',
              },
              {
                qText: '$32,971.94',
                qNum: 32971.94,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '378.04',
                qNum: 378.04,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Gorilla Cheese Spread',
                qNum: 'NaN',
                qElemNumber: 567,
                qState: 'O',
              },
              {
                qText: '$31,649.86',
                qNum: 31649.860000000008,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '41.65',
                qNum: 41.65,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Gorilla 1% Milk',
                qNum: 'NaN',
                qElemNumber: 3,
                qState: 'O',
              },
              {
                qText: '$31,236.12',
                qNum: 31236.119999999955,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '72.85',
                qNum: 72.85000000000001,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'High Top Dried Mushrooms',
                qNum: 'NaN',
                qElemNumber: 449,
                qState: 'O',
              },
              {
                qText: '$30,916.15',
                qNum: 30916.15000000005,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '70.8',
                qNum: 70.8,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Club Sharp Cheddar Cheese',
                qNum: 'NaN',
                qElemNumber: 94,
                qState: 'O',
              },
              {
                qText: '$30,884.11',
                qNum: 30884.10999999999,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '33.8',
                qNum: 33.8,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Gorilla Low Fat String Cheese',
                qNum: 'NaN',
                qElemNumber: 418,
                qState: 'O',
              },
              {
                qText: '$30,725.36',
                qNum: 30725.360000000015,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '9.62',
                qNum: 9.620000000000001,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Atomic Spicy Mints',
                qNum: 'NaN',
                qElemNumber: 353,
                qState: 'O',
              },
              {
                qText: '$30,217.09',
                qNum: 30217.08999999992,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '82.35',
                qNum: 82.35000000000001,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'BBB Best Chunky Peanut Butter',
                qNum: 'NaN',
                qElemNumber: 139,
                qState: 'O',
              },
              {
                qText: '$30,058.58',
                qNum: 30058.58000000003,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '79.14',
                qNum: 79.14,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Colony Blueberry Muffins',
                qNum: 'NaN',
                qElemNumber: 269,
                qState: 'O',
              },
              {
                qText: '$29,036.39',
                qNum: 29036.39000000005,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '106.06',
                qNum: 106.06,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Golden Waffles',
                qNum: 'NaN',
                qElemNumber: 120,
                qState: 'O',
              },
              {
                qText: '$28,855.68',
                qNum: 28855.680000000037,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '56.91',
                qNum: 56.910000000000004,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Just Right Chicken Ramen Soup',
                qNum: 'NaN',
                qElemNumber: 109,
                qState: 'O',
              },
              {
                qText: '$28,812.81',
                qNum: 28812.809999999983,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '225.21',
                qNum: 225.21,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Fabulous Cream Soda',
                qNum: 'NaN',
                qElemNumber: 135,
                qState: 'O',
              },
              {
                qText: '$27,419.90',
                qNum: 27419.90000000001,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '103.28',
                qNum: 103.28,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Just Right Canned Tuna in Water',
                qNum: 'NaN',
                qElemNumber: 110,
                qState: 'O',
              },
              {
                qText: '$26,506.41',
                qNum: 26506.40999999999,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '34.67',
                qNum: 34.67,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Gorilla String Cheese',
                qNum: 'NaN',
                qElemNumber: 138,
                qState: 'O',
              },
              {
                qText: '$26,275.19',
                qNum: 26275.190000000028,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '241.78',
                qNum: 241.78,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Fabulous Cola',
                qNum: 'NaN',
                qElemNumber: 140,
                qState: 'O',
              },
              {
                qText: '$25,947.01',
                qNum: 25947.01,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '8.75',
                qNum: 8.75,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'High Top Golden Delcious Apples',
                qNum: 'NaN',
                qElemNumber: 23,
                qState: 'O',
              },
              {
                qText: '$25,811.69',
                qNum: 25811.68999999989,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '16.71',
                qNum: 16.71,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Fast Dried Apples',
                qNum: 'NaN',
                qElemNumber: 80,
                qState: 'O',
              },
              {
                qText: '$24,835.75',
                qNum: 24835.749999999978,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '35.19',
                qNum: 35.19,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Red Spade Beef Bologna',
                qNum: 'NaN',
                qElemNumber: 20,
                qState: 'O',
              },
              {
                qText: '$24,674.70',
                qNum: 24674.699999999993,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '210.54',
                qNum: 210.54,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'BBB Best Apple Preserves',
                qNum: 'NaN',
                qElemNumber: 381,
                qState: 'O',
              },
              {
                qText: '$24,558.04',
                qNum: 24558.04000000001,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '26.08',
                qNum: 26.080000000000002,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Cutting Edge Sliced Ham',
                qNum: 'NaN',
                qElemNumber: 18,
                qState: 'O',
              },
              {
                qText: '$24,338.20',
                qNum: 24338.200000000008,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '118.23',
                qNum: 118.23,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Even Better Blueberry Yogurt',
                qNum: 'NaN',
                qElemNumber: 305,
                qState: 'O',
              },
              {
                qText: '$24,213.75',
                qNum: 24213.749999999996,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '24.31',
                qNum: 24.310000000000002,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Carlson Cheese Spread',
                qNum: 'NaN',
                qElemNumber: 221,
                qState: 'O',
              },
              {
                qText: '$24,046.29',
                qNum: 24046.289999999997,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '105.73',
                qNum: 105.73,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Best Choice Chocolate Chip Cookies',
                qNum: 'NaN',
                qElemNumber: 387,
                qState: 'O',
              },
              {
                qText: '$23,613.61',
                qNum: 23613.610000000008,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '17.96',
                qNum: 17.96,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Discover Spaghetti',
                qNum: 'NaN',
                qElemNumber: 70,
                qState: 'O',
              },
              {
                qText: '$23,327.32',
                qNum: 23327.320000000025,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '210.43',
                qNum: 210.43,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'BBB Best Grape Jelly',
                qNum: 'NaN',
                qElemNumber: 303,
                qState: 'O',
              },
              {
                qText: '$23,127.00',
                qNum: 23127.00000000001,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '87.12',
                qNum: 87.12,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Landslide French Roast Coffee',
                qNum: 'NaN',
                qElemNumber: 193,
                qState: 'O',
              },
              {
                qText: '$23,099.06',
                qNum: 23099.05999999999,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '9.51',
                qNum: 9.51,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Even Better Sharp Cheddar Cheese',
                qNum: 'NaN',
                qElemNumber: 647,
                qState: 'O',
              },
              {
                qText: '$22,709.87',
                qNum: 22709.869999999984,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '121.38',
                qNum: 121.38,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Big Time Frozen Peas',
                qNum: 'NaN',
                qElemNumber: 190,
                qState: 'O',
              },
              {
                qText: '$22,545.18',
                qNum: 22545.179999999975,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '39.22',
                qNum: 39.22,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Moms Corned Beef',
                qNum: 'NaN',
                qElemNumber: 162,
                qState: 'O',
              },
              {
                qText: '$22,421.22',
                qNum: 22421.220000000038,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '68.59',
                qNum: 68.59,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Nationeel Salted Pretzels',
                qNum: 'NaN',
                qElemNumber: 226,
                qState: 'O',
              },
              {
                qText: '$22,316.22',
                qNum: 22316.219999999983,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '28.57',
                qNum: 28.57,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Pearl Chardonnay',
                qNum: 'NaN',
                qElemNumber: 105,
                qState: 'O',
              },
              {
                qText: '$22,253.32',
                qNum: 22253.320000000003,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '74.21',
                qNum: 74.21000000000001,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Shady Lake Thai Rice',
                qNum: 'NaN',
                qElemNumber: 314,
                qState: 'O',
              },
              {
                qText: '$21,831.15',
                qNum: 21831.14999999996,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '14.81',
                qNum: 14.81,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Fast BBQ Potato Chips',
                qNum: 'NaN',
                qElemNumber: 144,
                qState: 'O',
              },
              {
                qText: '$21,566.73',
                qNum: 21566.730000000007,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '37.04',
                qNum: 37.04,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Tell Tale Mandarin Oranges',
                qNum: 'NaN',
                qElemNumber: 292,
                qState: 'O',
              },
              {
                qText: '$21,263.75',
                qNum: 21263.749999999956,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '100.85',
                qNum: 100.85000000000001,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Token Orange Juice',
                qNum: 'NaN',
                qElemNumber: 376,
                qState: 'O',
              },
              {
                qText: '$20,579.04',
                qNum: 20579.040000000005,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '23.59',
                qNum: 23.59,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Moms Sliced Ham',
                qNum: 'NaN',
                qElemNumber: 225,
                qState: 'O',
              },
              {
                qText: '$20,470.49',
                qNum: 20470.489999999954,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '168.91',
                qNum: 168.91,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Club Havarti Cheese',
                qNum: 'NaN',
                qElemNumber: 771,
                qState: 'O',
              },
              {
                qText: '$20,344.92',
                qNum: 20344.920000000006,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '55.57',
                qNum: 55.57,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Nationeel Grape Fruit Roll',
                qNum: 'NaN',
                qElemNumber: 298,
                qState: 'O',
              },
              {
                qText: '$20,090.55',
                qNum: 20090.550000000003,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '38.06',
                qNum: 38.06,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Big Time Home Style French Fries',
                qNum: 'NaN',
                qElemNumber: 148,
                qState: 'O',
              },
              {
                qText: '$19,982.90',
                qNum: 19982.89999999998,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '39.26',
                qNum: 39.26,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Good Imported Beer',
                qNum: 'NaN',
                qElemNumber: 143,
                qState: 'O',
              },
              {
                qText: '$19,855.76',
                qNum: 19855.760000000006,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '54.01',
                qNum: 54.01,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Gorilla Strawberry Yogurt',
                qNum: 'NaN',
                qElemNumber: 52,
                qState: 'O',
              },
              {
                qText: '$19,543.74',
                qNum: 19543.740000000005,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '30.38',
                qNum: 30.38,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Ebony Fuji Apples',
                qNum: 'NaN',
                qElemNumber: 128,
                qState: 'O',
              },
              {
                qText: '$19,515.82',
                qNum: 19515.82,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '310.31',
                qNum: 310.31,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Fabulous Apple Juice',
                qNum: 'NaN',
                qElemNumber: 698,
                qState: 'O',
              },
              {
                qText: '$19,105.17',
                qNum: 19105.170000000002,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '33.98',
                qNum: 33.980000000000004,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Even Better Buttermilk',
                qNum: 'NaN',
                qElemNumber: 681,
                qState: 'O',
              },
              {
                qText: '$19,051.86',
                qNum: 19051.86,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '56.62',
                qNum: 56.620000000000005,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Kiwi Scallops',
                qNum: 'NaN',
                qElemNumber: 658,
                qState: 'O',
              },
              {
                qText: '$18,721.48',
                qNum: 18721.47999999997,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '151.05',
                qNum: 151.05,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Club Head Cheese',
                qNum: 'NaN',
                qElemNumber: 609,
                qState: 'O',
              },
              {
                qText: '$18,679.81',
                qNum: 18679.80999999999,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '45.14',
                qNum: 45.14,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Tell Tale Macintosh Apples',
                qNum: 'NaN',
                qElemNumber: 149,
                qState: 'O',
              },
              {
                qText: '$18,546.24',
                qNum: 18546.239999999994,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '77.32',
                qNum: 77.32000000000001,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'High Top Asparagus',
                qNum: 'NaN',
                qElemNumber: 273,
                qState: 'O',
              },
              {
                qText: '$18,113.99',
                qNum: 18113.990000000013,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '21.13',
                qNum: 21.13,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Tell Tale Almonds',
                qNum: 'NaN',
                qElemNumber: 260,
                qState: 'O',
              },
              {
                qText: '$18,102.92',
                qNum: 18102.920000000002,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '7.63',
                qNum: 7.63,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Carlson String Cheese',
                qNum: 'NaN',
                qElemNumber: 116,
                qState: 'O',
              },
              {
                qText: '$17,824.76',
                qNum: 17824.760000000002,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '91.07',
                qNum: 91.07000000000001,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Gorilla Havarti Cheese',
                qNum: 'NaN',
                qElemNumber: 352,
                qState: 'O',
              },
              {
                qText: '$17,766.72',
                qNum: 17766.720000000005,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '54.67',
                qNum: 54.67,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Landslide Pepper',
                qNum: 'NaN',
                qElemNumber: 82,
                qState: 'O',
              },
              {
                qText: '$17,654.58',
                qNum: 17654.580000000027,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '1.12',
                qNum: 1.12,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Even Better String Cheese',
                qNum: 'NaN',
                qElemNumber: 332,
                qState: 'O',
              },
              {
                qText: '$17,048.92',
                qNum: 17048.919999999987,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '40.55',
                qNum: 40.550000000000004,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Tell Tale Garlic',
                qNum: 'NaN',
                qElemNumber: 313,
                qState: 'O',
              },
              {
                qText: '$17,029.83',
                qNum: 17029.829999999987,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '97.95',
                qNum: 97.95,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Gorilla Blueberry Yogurt',
                qNum: 'NaN',
                qElemNumber: 84,
                qState: 'O',
              },
              {
                qText: '$16,899.26',
                qNum: 16899.260000000006,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '60.41',
                qNum: 60.410000000000004,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Fast Low Fat Cookies',
                qNum: 'NaN',
                qElemNumber: 631,
                qState: 'O',
              },
              {
                qText: '$16,829.88',
                qNum: 16829.87999999995,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '59.04',
                qNum: 59.04,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Just Right Fancy Canned Oysters',
                qNum: 'NaN',
                qElemNumber: 399,
                qState: 'O',
              },
              {
                qText: '$16,165.21',
                qNum: 16165.21000000002,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '14.52',
                qNum: 14.52,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Blue Label Turkey Noodle Soup',
                qNum: 'NaN',
                qElemNumber: 181,
                qState: 'O',
              },
              {
                qText: '$16,080.21',
                qNum: 16080.210000000001,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '91.63',
                qNum: 91.63,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Super Apple Butter',
                qNum: 'NaN',
                qElemNumber: 189,
                qState: 'O',
              },
              {
                qText: '$16,051.52',
                qNum: 16051.520000000002,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '50.6',
                qNum: 50.6,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Atomic Semi-Sweet Chocolate Bar',
                qNum: 'NaN',
                qElemNumber: 361,
                qState: 'O',
              },
              {
                qText: '$16,005.41',
                qNum: 16005.41000000001,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '97.64',
                qNum: 97.64,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Colony English Muffins',
                qNum: 'NaN',
                qElemNumber: 236,
                qState: 'O',
              },
              {
                qText: '$15,942.62',
                qNum: 15942.620000000026,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '39.87',
                qNum: 39.87,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Club Cheese Spread',
                qNum: 'NaN',
                qElemNumber: 61,
                qState: 'O',
              },
              {
                qText: '$15,912.84',
                qNum: 15912.839999999982,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '3.75',
                qNum: 3.75,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Carlson Mild Cheddar Cheese',
                qNum: 'NaN',
                qElemNumber: 494,
                qState: 'O',
              },
              {
                qText: '$15,640.96',
                qNum: 15640.96,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: '20.98',
                qNum: 20.98,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Ebony Cantelope',
                qNum: 'NaN',
                qElemNumber: 68,
                qState: 'O',
              },
              {
                qText: '$15,602.83',
                qNum: 15602.829999999998,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
          ],
          qTails: [
            {
              qUp: 0,
              qDown: 0,
            },
          ],
          qArea: {
            qLeft: 0,
            qTop: 0,
            qWidth: 3,
            qHeight: 100,
          },
        },
      ],
    },
  ],
});
