export default () => ({
  type: 'sn-table',
  genericObjects: [
    {
      getLayout: {
        qInfo: {
          qId: 'QQxcpFg',
          qType: 'sn-table',
        },
        qMeta: {
          privileges: ['read', 'update', 'delete', 'exportdata'],
        },
        qSelectionInfo: {},
        qHyperCube: {
          qSize: {
            qcx: 4,
            qcy: 43,
          },
          qDimensionInfo: [
            {
              qFallbackTitle: 'Product',
              qApprMaxGlyphCount: 37,
              qCardinal: 824,
              qSortIndicator: 'A',
              qGroupFallbackTitles: ['Product'],
              qGroupPos: 0,
              qStateCounts: {
                qLocked: 0,
                qSelected: 0,
                qOption: 43,
                qDeselected: 0,
                qAlternative: 0,
                qExcluded: 781,
                qSelectedExcluded: 0,
                qLockedExcluded: 0,
              },
              qTags: ['$key', '$ascii', '$text'],
              qDimensionType: 'D',
              qGrouping: 'N',
              qNumFormat: {
                qType: 'R',
                qnDec: 14,
                qUseThou: 1,
                qFmt: '##############',
                qDec: '.',
                qThou: ',',
              },
              qIsAutoFormat: true,
              qGroupFieldDefs: ['Line Desc 1'],
              qMin: 'NaN',
              qMax: 'NaN',
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qCardinalities: {
                qCardinal: 824,
                qHypercubeCardinal: 43,
                qAllValuesCardinal: -1,
              },
              qLibraryId: 'pmresb',
              title: 'Product',
              othersLabel: 'Others',
              autoSort: true,
              textAlign: {
                auto: true,
                align: 'left',
              },
              columnWidth: {
                type: 'pixels',
                pixels: 120,
                percentage: 20,
              },
              cId: 'CTtz',
            },
            {
              qFallbackTitle: 'Product Group',
              qApprMaxGlyphCount: 19,
              qCardinal: 17,
              qSortIndicator: 'A',
              qGroupFallbackTitles: ['Product Group'],
              qGroupPos: 0,
              qStateCounts: {
                qLocked: 0,
                qSelected: 0,
                qOption: 12,
                qDeselected: 0,
                qAlternative: 0,
                qExcluded: 5,
                qSelectedExcluded: 0,
                qLockedExcluded: 0,
              },
              qTags: ['$ascii', '$text'],
              qDimensionType: 'D',
              qGrouping: 'N',
              qNumFormat: {
                qType: 'R',
                qnDec: 14,
                qUseThou: 1,
                qFmt: '##############',
                qDec: '.',
                qThou: ',',
              },
              qIsAutoFormat: true,
              qGroupFieldDefs: ['Product Group Desc'],
              qMin: 'NaN',
              qMax: 'NaN',
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qCardinalities: {
                qCardinal: 17,
                qHypercubeCardinal: 12,
                qAllValuesCardinal: -1,
              },
              qLibraryId: 'rAWLLGj',
              title: 'Product Group',
              coloring: {
                colorMapRef: 'rAWLLGj',
                changeHash: '0.42084647290569577',
              },
              othersLabel: 'Others',
              autoSort: true,
              textAlign: {
                auto: true,
                align: 'left',
              },
              columnWidth: {
                type: 'pixels',
                pixels: 120,
                percentage: 20,
              },
              cId: 'QZRpVg',
            },
            {
              qFallbackTitle: 'Long values',
              qApprMaxGlyphCount: 63,
              qCardinal: 824,
              qSortIndicator: 'A',
              qGroupFallbackTitles: ['Long values'],
              qGroupPos: 0,
              qStateCounts: {
                qLocked: 0,
                qSelected: 0,
                qOption: 43,
                qDeselected: 0,
                qAlternative: 0,
                qExcluded: 781,
                qSelectedExcluded: 0,
                qLockedExcluded: 0,
              },
              qTags: ['$ascii', '$text'],
              qDimensionType: 'D',
              qGrouping: 'N',
              qNumFormat: {
                qType: 'U',
                qnDec: 0,
                qUseThou: 0,
              },
              qIsAutoFormat: true,
              qGroupFieldDefs: ["=[Line Desc 1]&' and some loooooooong text'"],
              qMin: 'NaN',
              qMax: 'NaN',
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qCardinalities: {
                qCardinal: 824,
                qHypercubeCardinal: 43,
                qAllValuesCardinal: -1,
              },
              qLibraryId: 'LJrtrp',
              title: 'Long values',
              coloring: {
                changeHash: '0.7165069500856971',
                hasValueColors: false,
              },
              othersLabel: 'Others',
              autoSort: true,
              textAlign: {
                auto: true,
                align: 'left',
              },
              columnWidth: {
                type: 'pixels',
                pixels: 120,
                percentage: 20,
              },
              cId: 'GgXpAP',
            },
          ],
          qMeasureInfo: [
            {
              qFallbackTitle: '=1.123456789123456789',
              qApprMaxGlyphCount: 20,
              qCardinal: 0,
              qSortIndicator: 'D',
              qNumFormat: {
                qType: 'U',
                qnDec: 0,
                qUseThou: 0,
              },
              qMin: 1.1234567891234568,
              qMax: 1.1234567891234568,
              qIsAutoFormat: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qTrendLines: [],
              numFormatFromTemplate: true,
              autoSort: true,
              textAlign: {
                auto: true,
                align: 'left',
              },
              columnWidth: {
                type: 'pixels',
                pixels: 120,
                percentage: 20,
              },
              cId: 'KUdHq',
            },
          ],
          qEffectiveInterColumnSortOrder: [0, 1, 3, 2],
          qGrandTotalRow: [
            {
              qText: '1.123456789123456789',
              qNum: 1.1234567891234568,
              qElemNumber: -1,
              qState: 'X',
              qIsTotalCell: true,
            },
          ],
          qDataPages: [
            {
              qMatrix: [
                [
                  {
                    qText: 'American Cole Slaw',
                    qNum: 'NaN',
                    qElemNumber: 334,
                    qState: 'O',
                  },
                  {
                    qText: 'Deli',
                    qNum: 'NaN',
                    qElemNumber: 8,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'American Cole Slaw and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 334,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'American Foot-Long Hot Dogs',
                    qNum: 'NaN',
                    qElemNumber: 535,
                    qState: 'O',
                  },
                  {
                    qText: 'Deli',
                    qNum: 'NaN',
                    qElemNumber: 8,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'American Foot-Long Hot Dogs and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 535,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'American Pimento Loaf',
                    qNum: 'NaN',
                    qElemNumber: 415,
                    qState: 'O',
                  },
                  {
                    qText: 'Baked Goods',
                    qNum: 'NaN',
                    qElemNumber: 1,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'American Pimento Loaf and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 415,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'American Roasted Chicken',
                    qNum: 'NaN',
                    qElemNumber: 509,
                    qState: 'O',
                  },
                  {
                    qText: 'Deli',
                    qNum: 'NaN',
                    qElemNumber: 8,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'American Roasted Chicken and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 509,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Atomic Mint Chocolate Bar',
                    qNum: 'NaN',
                    qElemNumber: 187,
                    qState: 'O',
                  },
                  {
                    qText: 'Snacks',
                    qNum: 'NaN',
                    qElemNumber: 15,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Atomic Mint Chocolate Bar and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 187,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Big Time Fajita French Fries',
                    qNum: 'NaN',
                    qElemNumber: 81,
                    qState: 'O',
                  },
                  {
                    qText: 'Frozen Foods',
                    qNum: 'NaN',
                    qElemNumber: 10,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Big Time Fajita French Fries and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 81,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Blue Label Canned String Beans',
                    qNum: 'NaN',
                    qElemNumber: 513,
                    qState: 'O',
                  },
                  {
                    qText: 'Canned Foods',
                    qNum: 'NaN',
                    qElemNumber: 5,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Blue Label Canned String Beans and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 513,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Blue Label Chicken Soup',
                    qNum: 'NaN',
                    qElemNumber: 634,
                    qState: 'O',
                  },
                  {
                    qText: 'Canned Foods',
                    qNum: 'NaN',
                    qElemNumber: 5,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Blue Label Chicken Soup and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 634,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Blue Label Regular Ramen Soup',
                    qNum: 'NaN',
                    qElemNumber: 141,
                    qState: 'O',
                  },
                  {
                    qText: 'Canned Foods',
                    qNum: 'NaN',
                    qElemNumber: 5,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Blue Label Regular Ramen Soup and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 141,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Bravo Canned Tomatos',
                    qNum: 'NaN',
                    qElemNumber: 44,
                    qState: 'O',
                  },
                  {
                    qText: 'Canned Foods',
                    qNum: 'NaN',
                    qElemNumber: 5,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Bravo Canned Tomatos and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 44,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Club Head Cheese',
                    qNum: 'NaN',
                    qElemNumber: 609,
                    qState: 'O',
                  },
                  {
                    qText: 'Dairy',
                    qNum: 'NaN',
                    qElemNumber: 7,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Club Head Cheese and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 609,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Ebony Onions',
                    qNum: 'NaN',
                    qElemNumber: 57,
                    qState: 'O',
                  },
                  {
                    qText: 'Produce',
                    qNum: 'NaN',
                    qElemNumber: 12,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Ebony Onions and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 57,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Ebony Prepared Salad',
                    qNum: 'NaN',
                    qElemNumber: 127,
                    qState: 'O',
                  },
                  {
                    qText: 'Produce',
                    qNum: 'NaN',
                    qElemNumber: 12,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Ebony Prepared Salad and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 127,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Even Better Havarti Cheese',
                    qNum: 'NaN',
                    qElemNumber: 421,
                    qState: 'O',
                  },
                  {
                    qText: 'Dairy',
                    qNum: 'NaN',
                    qElemNumber: 7,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Even Better Havarti Cheese and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 421,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Even Better Low Fat String Cheese',
                    qNum: 'NaN',
                    qElemNumber: 383,
                    qState: 'O',
                  },
                  {
                    qText: 'Dairy',
                    qNum: 'NaN',
                    qElemNumber: 7,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Even Better Low Fat String Cheese and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 383,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Even Better Muenster Cheese',
                    qNum: 'NaN',
                    qElemNumber: 561,
                    qState: 'O',
                  },
                  {
                    qText: 'Dairy',
                    qNum: 'NaN',
                    qElemNumber: 7,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Even Better Muenster Cheese and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 561,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Excellent Apple Juice',
                    qNum: 'NaN',
                    qElemNumber: 797,
                    qState: 'O',
                  },
                  {
                    qText: 'Beverages',
                    qNum: 'NaN',
                    qElemNumber: 3,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Excellent Apple Juice and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 797,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Fast Cheese Dip',
                    qNum: 'NaN',
                    qElemNumber: 26,
                    qState: 'O',
                  },
                  {
                    qText: 'Snack Foods',
                    qNum: 'NaN',
                    qElemNumber: 14,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Fast Cheese Dip and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 26,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Fast Dried Apples',
                    qNum: 'NaN',
                    qElemNumber: 80,
                    qState: 'O',
                  },
                  {
                    qText: 'Snack Foods',
                    qNum: 'NaN',
                    qElemNumber: 14,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Fast Dried Apples and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 80,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Golden Blueberry Waffles',
                    qNum: 'NaN',
                    qElemNumber: 605,
                    qState: 'O',
                  },
                  {
                    qText: 'Frozen Foods',
                    qNum: 'NaN',
                    qElemNumber: 10,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Golden Blueberry Waffles and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 605,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Golden Fajita French Fries',
                    qNum: 'NaN',
                    qElemNumber: 518,
                    qState: 'O',
                  },
                  {
                    qText: 'Frozen Foods',
                    qNum: 'NaN',
                    qElemNumber: 10,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Golden Fajita French Fries and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 518,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Golden Frozen Cheese Pizza',
                    qNum: 'NaN',
                    qElemNumber: 131,
                    qState: 'O',
                  },
                  {
                    qText: 'Frozen Foods',
                    qNum: 'NaN',
                    qElemNumber: 10,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Golden Frozen Cheese Pizza and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 131,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Golden Frozen Pancakes',
                    qNum: 'NaN',
                    qElemNumber: 423,
                    qState: 'O',
                  },
                  {
                    qText: 'Frozen Foods',
                    qNum: 'NaN',
                    qElemNumber: 10,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Golden Frozen Pancakes and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 423,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Golden Frozen Pepperoni Pizza',
                    qNum: 'NaN',
                    qElemNumber: 50,
                    qState: 'O',
                  },
                  {
                    qText: 'Frozen Foods',
                    qNum: 'NaN',
                    qElemNumber: 10,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Golden Frozen Pepperoni Pizza and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 50,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Golden Low Fat Waffles',
                    qNum: 'NaN',
                    qElemNumber: 204,
                    qState: 'O',
                  },
                  {
                    qText: 'Frozen Foods',
                    qNum: 'NaN',
                    qElemNumber: 10,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Golden Low Fat Waffles and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 204,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Golden Turkey TV Dinner',
                    qNum: 'NaN',
                    qElemNumber: 195,
                    qState: 'O',
                  },
                  {
                    qText: 'Frozen Foods',
                    qNum: 'NaN',
                    qElemNumber: 10,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Golden Turkey TV Dinner and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 195,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'High Top Golden Delcious Apples',
                    qNum: 'NaN',
                    qElemNumber: 23,
                    qState: 'O',
                  },
                  {
                    qText: 'Produce',
                    qNum: 'NaN',
                    qElemNumber: 12,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'High Top Golden Delcious Apples and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 23,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'High Top Macintosh Apples',
                    qNum: 'NaN',
                    qElemNumber: 96,
                    qState: 'O',
                  },
                  {
                    qText: 'Produce',
                    qNum: 'NaN',
                    qElemNumber: 12,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'High Top Macintosh Apples and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 96,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Imagine Ice Cream',
                    qNum: 'NaN',
                    qElemNumber: 691,
                    qState: 'O',
                  },
                  {
                    qText: 'Frozen Foods',
                    qNum: 'NaN',
                    qElemNumber: 10,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Imagine Ice Cream and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 691,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Landslide Chunky Peanut Butter',
                    qNum: 'NaN',
                    qElemNumber: 194,
                    qState: 'O',
                  },
                  {
                    qText: 'Baking Goods',
                    qNum: 'NaN',
                    qElemNumber: 2,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Landslide Chunky Peanut Butter and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 194,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Landslide Columbian Coffee',
                    qNum: 'NaN',
                    qElemNumber: 318,
                    qState: 'O',
                  },
                  {
                    qText: 'Beverages',
                    qNum: 'NaN',
                    qElemNumber: 3,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Landslide Columbian Coffee and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 318,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Moms Chicken Hot Dogs',
                    qNum: 'NaN',
                    qElemNumber: 16,
                    qState: 'O',
                  },
                  {
                    qText: 'Deli',
                    qNum: 'NaN',
                    qElemNumber: 8,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Moms Chicken Hot Dogs and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 16,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Moms Pimento Loaf',
                    qNum: 'NaN',
                    qElemNumber: 786,
                    qState: 'O',
                  },
                  {
                    qText: 'Deli',
                    qNum: 'NaN',
                    qElemNumber: 8,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Moms Pimento Loaf and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 786,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Moms Potato Salad',
                    qNum: 'NaN',
                    qElemNumber: 275,
                    qState: 'O',
                  },
                  {
                    qText: 'Deli',
                    qNum: 'NaN',
                    qElemNumber: 8,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Moms Potato Salad and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 275,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Pearl Chardonnay',
                    qNum: 'NaN',
                    qElemNumber: 105,
                    qState: 'O',
                  },
                  {
                    qText: 'Alcoholic Beverages',
                    qNum: 'NaN',
                    qElemNumber: 0,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Pearl Chardonnay and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 105,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Red Spade Foot-Long Hot Dogs',
                    qNum: 'NaN',
                    qElemNumber: 322,
                    qState: 'O',
                  },
                  {
                    qText: 'Deli',
                    qNum: 'NaN',
                    qElemNumber: 8,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Red Spade Foot-Long Hot Dogs and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 322,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Red Spade Low Fat Cole Slaw',
                    qNum: 'NaN',
                    qElemNumber: 271,
                    qState: 'O',
                  },
                  {
                    qText: 'Deli',
                    qNum: 'NaN',
                    qElemNumber: 8,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Red Spade Low Fat Cole Slaw and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 271,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Tell Tale Asparagus',
                    qNum: 'NaN',
                    qElemNumber: 228,
                    qState: 'O',
                  },
                  {
                    qText: 'Produce',
                    qNum: 'NaN',
                    qElemNumber: 12,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Tell Tale Asparagus and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 228,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Tell Tale Firm Tofu',
                    qNum: 'NaN',
                    qElemNumber: 173,
                    qState: 'O',
                  },
                  {
                    qText: 'Produce',
                    qNum: 'NaN',
                    qElemNumber: 12,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Tell Tale Firm Tofu and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 173,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Tell Tale Sweet Peas',
                    qNum: 'NaN',
                    qElemNumber: 710,
                    qState: 'O',
                  },
                  {
                    qText: 'Produce',
                    qNum: 'NaN',
                    qElemNumber: 12,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Tell Tale Sweet Peas and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 710,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Token Apple Drink',
                    qNum: 'NaN',
                    qElemNumber: 371,
                    qState: 'O',
                  },
                  {
                    qText: 'Beverages',
                    qNum: 'NaN',
                    qElemNumber: 3,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Token Apple Drink and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 371,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Urban Large Eggs',
                    qNum: 'NaN',
                    qElemNumber: 277,
                    qState: 'O',
                  },
                  {
                    qText: 'Eggs',
                    qNum: 'NaN',
                    qElemNumber: 9,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Urban Large Eggs and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 277,
                    qState: 'O',
                  },
                ],
                [
                  {
                    qText: 'Urban Small Brown Eggs',
                    qNum: 'NaN',
                    qElemNumber: 291,
                    qState: 'O',
                  },
                  {
                    qText: 'Eggs',
                    qNum: 'NaN',
                    qElemNumber: 9,
                    qState: 'O',
                  },
                  {
                    qText: '1.123456789123456789',
                    qNum: 1.1234567891234568,
                    qElemNumber: 0,
                    qState: 'L',
                  },
                  {
                    qText: 'Urban Small Brown Eggs and some loooooooong text',
                    qNum: 'NaN',
                    qElemNumber: 291,
                    qState: 'O',
                  },
                ],
              ],
              qTails: [
                {
                  qUp: 0,
                  qDown: 0,
                },
                {
                  qUp: 0,
                  qDown: 0,
                },
                {
                  qUp: 0,
                  qDown: 0,
                },
              ],
              qArea: {
                qLeft: 0,
                qTop: 0,
                qWidth: 4,
                qHeight: 43,
              },
            },
          ],
          qPivotDataPages: [],
          qStackedDataPages: [],
          qMode: 'S',
          qNoOfLeftDims: -1,
          qTreeNodesOnDim: [],
          qColumnOrder: [0, 1, 3, 2],
          columnWidths: [-1, -1, -1, -1],
        },
        showTitles: true,
        title: '',
        subtitle: '',
        footnote: '',
        disableNavMenu: false,
        showDetails: true,
        showDetailsExpression: false,
        components: [],
        totals: {
          show: true,
          position: 'noTotals',
          label: 'Totals with a loooooooooooooooong label and some more text',
        },
        usePagination: false,
        enableChartExploration: false,
        chartExploration: {
          menuVisibility: 'auto',
        },
        visualization: 'sn-table',
        version: '"2.0.0"',
        extensionMeta: {
          translationKey: '',
          icon: 'table',
          iconChar: 'puzzle',
          isLibraryItem: true,
          visible: true,
          name: 'Straight table',
          description:
            'Display several measure values for each dimension value. Show the totals for each measure. Sort columns and rows alphabetically or numerically. Change sorting during analysis. Chart exploration allows for adding and removing columns in analysis.',
          template: 'sn-table',
          iconPath:
            'M14.5,9 L13,9 L13,3.3 C13,3.1 12.9,3 12.7,3 L8,3 L8,1.5 C8,0.7 7.3,0 6.5,0 C5.7,0 5,0.7 5,1.5 L5,3 L0.3,3 C0.1,3 0,3.1 0,3.3 L0,9 L1.5,9 C2.3,9 3,9.7 3,10.5 C3,11.3 2.3,12 1.5,12 L0,12 L0,15.7 C0,15.9 0.1,16 0.3,16 L5,16 L5,14.5 C5,13.7 5.7,13 6.5,13 C7.3,13 8,13.7 8,14.5 L8,16 L12.7,16 C12.9,16 13,15.9 13,15.7 L13,12 L14.5,12 C15.3,12 16,11.3 16,10.5 C16,9.7 15.3,9 14.5,9 Z',
          isThirdParty: true,
          version: '2.0.0',
          author: 'QlikTech International AB',
          type: 'visualization',
          supernova: true,
        },
      },
      getHyperCubeData: [
        {
          qMatrix: [
            [
              {
                qText: 'American Cole Slaw',
                qNum: 'NaN',
                qElemNumber: 334,
                qState: 'O',
              },
              {
                qText: 'Deli',
                qNum: 'NaN',
                qElemNumber: 8,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'American Cole Slaw and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 334,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'American Foot-Long Hot Dogs',
                qNum: 'NaN',
                qElemNumber: 535,
                qState: 'O',
              },
              {
                qText: 'Deli',
                qNum: 'NaN',
                qElemNumber: 8,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'American Foot-Long Hot Dogs and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 535,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'American Pimento Loaf',
                qNum: 'NaN',
                qElemNumber: 415,
                qState: 'O',
              },
              {
                qText: 'Baked Goods',
                qNum: 'NaN',
                qElemNumber: 1,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'American Pimento Loaf and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 415,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'American Roasted Chicken',
                qNum: 'NaN',
                qElemNumber: 509,
                qState: 'O',
              },
              {
                qText: 'Deli',
                qNum: 'NaN',
                qElemNumber: 8,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'American Roasted Chicken and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 509,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Atomic Mint Chocolate Bar',
                qNum: 'NaN',
                qElemNumber: 187,
                qState: 'O',
              },
              {
                qText: 'Snacks',
                qNum: 'NaN',
                qElemNumber: 15,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Atomic Mint Chocolate Bar and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 187,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Big Time Fajita French Fries',
                qNum: 'NaN',
                qElemNumber: 81,
                qState: 'O',
              },
              {
                qText: 'Frozen Foods',
                qNum: 'NaN',
                qElemNumber: 10,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Big Time Fajita French Fries and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 81,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Blue Label Canned String Beans',
                qNum: 'NaN',
                qElemNumber: 513,
                qState: 'O',
              },
              {
                qText: 'Canned Foods',
                qNum: 'NaN',
                qElemNumber: 5,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Blue Label Canned String Beans and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 513,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Blue Label Chicken Soup',
                qNum: 'NaN',
                qElemNumber: 634,
                qState: 'O',
              },
              {
                qText: 'Canned Foods',
                qNum: 'NaN',
                qElemNumber: 5,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Blue Label Chicken Soup and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 634,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Blue Label Regular Ramen Soup',
                qNum: 'NaN',
                qElemNumber: 141,
                qState: 'O',
              },
              {
                qText: 'Canned Foods',
                qNum: 'NaN',
                qElemNumber: 5,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Blue Label Regular Ramen Soup and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 141,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Bravo Canned Tomatos',
                qNum: 'NaN',
                qElemNumber: 44,
                qState: 'O',
              },
              {
                qText: 'Canned Foods',
                qNum: 'NaN',
                qElemNumber: 5,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Bravo Canned Tomatos and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 44,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Club Head Cheese',
                qNum: 'NaN',
                qElemNumber: 609,
                qState: 'O',
              },
              {
                qText: 'Dairy',
                qNum: 'NaN',
                qElemNumber: 7,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Club Head Cheese and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 609,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Ebony Onions',
                qNum: 'NaN',
                qElemNumber: 57,
                qState: 'O',
              },
              {
                qText: 'Produce',
                qNum: 'NaN',
                qElemNumber: 12,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Ebony Onions and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 57,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Ebony Prepared Salad',
                qNum: 'NaN',
                qElemNumber: 127,
                qState: 'O',
              },
              {
                qText: 'Produce',
                qNum: 'NaN',
                qElemNumber: 12,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Ebony Prepared Salad and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 127,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Even Better Havarti Cheese',
                qNum: 'NaN',
                qElemNumber: 421,
                qState: 'O',
              },
              {
                qText: 'Dairy',
                qNum: 'NaN',
                qElemNumber: 7,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Even Better Havarti Cheese and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 421,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Even Better Low Fat String Cheese',
                qNum: 'NaN',
                qElemNumber: 383,
                qState: 'O',
              },
              {
                qText: 'Dairy',
                qNum: 'NaN',
                qElemNumber: 7,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Even Better Low Fat String Cheese and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 383,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Even Better Muenster Cheese',
                qNum: 'NaN',
                qElemNumber: 561,
                qState: 'O',
              },
              {
                qText: 'Dairy',
                qNum: 'NaN',
                qElemNumber: 7,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Even Better Muenster Cheese and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 561,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Excellent Apple Juice',
                qNum: 'NaN',
                qElemNumber: 797,
                qState: 'O',
              },
              {
                qText: 'Beverages',
                qNum: 'NaN',
                qElemNumber: 3,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Excellent Apple Juice and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 797,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Fast Cheese Dip',
                qNum: 'NaN',
                qElemNumber: 26,
                qState: 'O',
              },
              {
                qText: 'Snack Foods',
                qNum: 'NaN',
                qElemNumber: 14,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Fast Cheese Dip and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 26,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Fast Dried Apples',
                qNum: 'NaN',
                qElemNumber: 80,
                qState: 'O',
              },
              {
                qText: 'Snack Foods',
                qNum: 'NaN',
                qElemNumber: 14,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Fast Dried Apples and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 80,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Golden Blueberry Waffles',
                qNum: 'NaN',
                qElemNumber: 605,
                qState: 'O',
              },
              {
                qText: 'Frozen Foods',
                qNum: 'NaN',
                qElemNumber: 10,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Golden Blueberry Waffles and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 605,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Golden Fajita French Fries',
                qNum: 'NaN',
                qElemNumber: 518,
                qState: 'O',
              },
              {
                qText: 'Frozen Foods',
                qNum: 'NaN',
                qElemNumber: 10,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Golden Fajita French Fries and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 518,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Golden Frozen Cheese Pizza',
                qNum: 'NaN',
                qElemNumber: 131,
                qState: 'O',
              },
              {
                qText: 'Frozen Foods',
                qNum: 'NaN',
                qElemNumber: 10,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Golden Frozen Cheese Pizza and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 131,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Golden Frozen Pancakes',
                qNum: 'NaN',
                qElemNumber: 423,
                qState: 'O',
              },
              {
                qText: 'Frozen Foods',
                qNum: 'NaN',
                qElemNumber: 10,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Golden Frozen Pancakes and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 423,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Golden Frozen Pepperoni Pizza',
                qNum: 'NaN',
                qElemNumber: 50,
                qState: 'O',
              },
              {
                qText: 'Frozen Foods',
                qNum: 'NaN',
                qElemNumber: 10,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Golden Frozen Pepperoni Pizza and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 50,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Golden Low Fat Waffles',
                qNum: 'NaN',
                qElemNumber: 204,
                qState: 'O',
              },
              {
                qText: 'Frozen Foods',
                qNum: 'NaN',
                qElemNumber: 10,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Golden Low Fat Waffles and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 204,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Golden Turkey TV Dinner',
                qNum: 'NaN',
                qElemNumber: 195,
                qState: 'O',
              },
              {
                qText: 'Frozen Foods',
                qNum: 'NaN',
                qElemNumber: 10,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Golden Turkey TV Dinner and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 195,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'High Top Golden Delcious Apples',
                qNum: 'NaN',
                qElemNumber: 23,
                qState: 'O',
              },
              {
                qText: 'Produce',
                qNum: 'NaN',
                qElemNumber: 12,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'High Top Golden Delcious Apples and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 23,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'High Top Macintosh Apples',
                qNum: 'NaN',
                qElemNumber: 96,
                qState: 'O',
              },
              {
                qText: 'Produce',
                qNum: 'NaN',
                qElemNumber: 12,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'High Top Macintosh Apples and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 96,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Imagine Ice Cream',
                qNum: 'NaN',
                qElemNumber: 691,
                qState: 'O',
              },
              {
                qText: 'Frozen Foods',
                qNum: 'NaN',
                qElemNumber: 10,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Imagine Ice Cream and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 691,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Landslide Chunky Peanut Butter',
                qNum: 'NaN',
                qElemNumber: 194,
                qState: 'O',
              },
              {
                qText: 'Baking Goods',
                qNum: 'NaN',
                qElemNumber: 2,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Landslide Chunky Peanut Butter and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 194,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Landslide Columbian Coffee',
                qNum: 'NaN',
                qElemNumber: 318,
                qState: 'O',
              },
              {
                qText: 'Beverages',
                qNum: 'NaN',
                qElemNumber: 3,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Landslide Columbian Coffee and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 318,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Moms Chicken Hot Dogs',
                qNum: 'NaN',
                qElemNumber: 16,
                qState: 'O',
              },
              {
                qText: 'Deli',
                qNum: 'NaN',
                qElemNumber: 8,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Moms Chicken Hot Dogs and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 16,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Moms Pimento Loaf',
                qNum: 'NaN',
                qElemNumber: 786,
                qState: 'O',
              },
              {
                qText: 'Deli',
                qNum: 'NaN',
                qElemNumber: 8,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Moms Pimento Loaf and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 786,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Moms Potato Salad',
                qNum: 'NaN',
                qElemNumber: 275,
                qState: 'O',
              },
              {
                qText: 'Deli',
                qNum: 'NaN',
                qElemNumber: 8,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Moms Potato Salad and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 275,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Pearl Chardonnay',
                qNum: 'NaN',
                qElemNumber: 105,
                qState: 'O',
              },
              {
                qText: 'Alcoholic Beverages',
                qNum: 'NaN',
                qElemNumber: 0,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Pearl Chardonnay and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 105,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Red Spade Foot-Long Hot Dogs',
                qNum: 'NaN',
                qElemNumber: 322,
                qState: 'O',
              },
              {
                qText: 'Deli',
                qNum: 'NaN',
                qElemNumber: 8,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Red Spade Foot-Long Hot Dogs and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 322,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Red Spade Low Fat Cole Slaw',
                qNum: 'NaN',
                qElemNumber: 271,
                qState: 'O',
              },
              {
                qText: 'Deli',
                qNum: 'NaN',
                qElemNumber: 8,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Red Spade Low Fat Cole Slaw and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 271,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Tell Tale Asparagus',
                qNum: 'NaN',
                qElemNumber: 228,
                qState: 'O',
              },
              {
                qText: 'Produce',
                qNum: 'NaN',
                qElemNumber: 12,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Tell Tale Asparagus and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 228,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Tell Tale Firm Tofu',
                qNum: 'NaN',
                qElemNumber: 173,
                qState: 'O',
              },
              {
                qText: 'Produce',
                qNum: 'NaN',
                qElemNumber: 12,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Tell Tale Firm Tofu and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 173,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Tell Tale Sweet Peas',
                qNum: 'NaN',
                qElemNumber: 710,
                qState: 'O',
              },
              {
                qText: 'Produce',
                qNum: 'NaN',
                qElemNumber: 12,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Tell Tale Sweet Peas and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 710,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Token Apple Drink',
                qNum: 'NaN',
                qElemNumber: 371,
                qState: 'O',
              },
              {
                qText: 'Beverages',
                qNum: 'NaN',
                qElemNumber: 3,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Token Apple Drink and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 371,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Urban Large Eggs',
                qNum: 'NaN',
                qElemNumber: 277,
                qState: 'O',
              },
              {
                qText: 'Eggs',
                qNum: 'NaN',
                qElemNumber: 9,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Urban Large Eggs and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 277,
                qState: 'O',
              },
            ],
            [
              {
                qText: 'Urban Small Brown Eggs',
                qNum: 'NaN',
                qElemNumber: 291,
                qState: 'O',
              },
              {
                qText: 'Eggs',
                qNum: 'NaN',
                qElemNumber: 9,
                qState: 'O',
              },
              {
                qText: '1.123456789123456789',
                qNum: 1.1234567891234568,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: 'Urban Small Brown Eggs and some loooooooong text',
                qNum: 'NaN',
                qElemNumber: 291,
                qState: 'O',
              },
            ],
          ],
          qTails: [
            {
              qUp: 0,
              qDown: 0,
            },
            {
              qUp: 0,
              qDown: 0,
            },
            {
              qUp: 0,
              qDown: 0,
            },
          ],
          qArea: {
            qLeft: 0,
            qTop: 0,
            qWidth: 4,
            qHeight: 43,
          },
        },
      ],
    },
  ],
});
