const MIN_BODY_ROW_HEIGHT = 24;

const MIN_HEADER_HEIGHT = 32;

const PAGINATION_HEIGHT = 41;

const MAX_PAGE_SIZE = 250000;

const ROW_DATA_BUFFER_SIZE = 25;

const COLUMN_DATA_BUFFER_SIZE = 5;

const PADDING_LEFT_RIGHT = 12;

const PADDING_TOP_BOTTOM = 4;

const BORDER_WIDTH = 1;

const MAX_NBR_LINES_OF_TEXT = 50;

export {
  MIN_BODY_ROW_HEIGHT,
  MIN_HEADER_HEIGHT,
  MAX_PAGE_SIZE,
  PAGINATION_HEIGHT,
  ROW_DATA_BUFFER_SIZE,
  COLUMN_DATA_BUFFER_SIZE,
  PADDING_LEFT_RIGHT,
  PADDING_TOP_BOTTOM,
  BORDER_WIDTH,
  MAX_NBR_LINES_OF_TEXT,
};
