const MIN_BODY_ROW_HEIGHT = 24;

const MIN_HEADER_HEIGHT = 32;

const PAGINATION_HEIGHT = 41;

const MAX_PAGE_SIZE = 250000;

const ROW_DATA_BUFFER_SIZE = 25;

const COLUMN_DATA_BUFFER_SIZE = 5;

export {
  MIN_BODY_ROW_HEIGHT,
  MIN_HEADER_HEIGHT,
  MAX_PAGE_SIZE,
  PAGINATION_HEIGHT,
  ROW_DATA_BUFFER_SIZE,
  COLUMN_DATA_BUFFER_SIZE,
};
