name: Build
on:
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        required: true
        default: false

  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build:
    uses: qlik-oss/sn-gh-workflows/.github/workflows/build.yaml@v2
    secrets: inherit
    with:
      release: ${{ inputs.release || false}}
      api_specification_path: api-specifications/properties.json
